# Work dir
root = "."
tmp_dir = "tmp"

[build]
# On windows platform
# bin = "./tmp/main.exe"
# cmd = "go build -o ./tmp/main.exe ."
# On Unix, Linux platform
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ."
# Delay time to trigger build
delay = 1000
# Ignored the following extension or directory
exclude_dir = ["assets", "tmp", "vendor", "public/uploads"]
# Ignored te following file
exclude_file = []
# Use regex ignore file
exclude_regex = []
# Ignore unchanged files
exclude_unchanged = false
# Monitoring System Change Directory
follow_symlink = false
# Custom parameters
full_bin = ""
# Listen to the following specified directory
include_dir = []
# Listen for files with the following extensions
include_file = ["go", "tpl", "tmpl", "html", "gohtml", "env"]
# kill command delay
kill_delay = "0s"
# air log file name
log = "air.log"
# Send a system interrupt signal before kill(Microsoft Windows do not support)
send_interrupt = false
# End operation when error occurs
stop_on_error = true
# Command additional parameters
args_bin = []

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[log]
# show log time
time = false

[misc]
# delete tmp directory on exit
clean_on_exit = false
